#+title: EmacsOpen.app (Pre-Pre-Pre-Alpha)
* Main idea
"Open thing in Emacs, do what I mean."

Share and open files, web links, web page selection (Safari), and =org-protocol://= links in Emacs on macOS, starting the Emacs daemon and opening a frame if necessary.
* Status: Just starting
- Some initial skeleton code.
- Expect frequent history rewrites.
- Not even close to useful.
* CLI command =emacsopen=
- =ensure-client= (after which =emacsclient= should be ready, else error)
- =ensure-frame= (implies =ensure-client=)
- =activate-frame= (implies =ensure-frame=)
- =open-files [FILE...]=  (implies =activate-frame=)
- =open-org-protocol org-protocol://...= (implies =activate-frame=)
* Target Emacs flavours
Targetting macOS Emacs flavours which run in daemon mode via =brew service=, communicating via =emacsclient=.

Focusing on [[https://github.com/d12frosted/homebrew-emacs-plus][Emacs Plus]] v30 initially, but all related Emacs formulas should work the same way.
* Roadmap
- Address potential roadblocks to see if viable at all
  - Can an unsigned macOS app invoke =emacsclient= to connect to Emacs when running?
    - Potential issues with permissions, and environment variables. Fails within Shortcuts.app.
  - Can an unsigned macOS app start and stop a brew service? Potential permissions issues.
- Skeleton app
  - Use icon from [[https://github.com/emacsfodder/emacs-icons-project][emacsfodder/emacs-icons-project]]
  - Skeleton =emacsopen= command
- Read config
  - Location of =emacsclient=
  - Name of brew service to use
  - =org-protocol://= scheme config
- Handle opening files via drag and drop and opening via Finder (with frame already open)
- Handle =org-protocol://= links (with frame already open)
  - To open an existing Org node by its Org ID
  - To capture a web page, with url, title, and optional selected text
  - To trigger =org-capture=, eg to add an inbox item
- Always activate Emacs top window
- Open frame if necessary
- Start daemon if necessary, waiting until ready for =emacsclient= commands
- =open -a EmacsOpen= should open Emacs, creating a frame if necessary, and activate Emacs
- Ensure useful for emacs restart
  Eg support ~brew services stop emacs-plus@30; doom sync; emacsopen activate-frame~
- Act as a share target to invoke the command org-protocol convention of url, title, and text.
- Act as a Safari extension with support for sharing current page (including text selection) via =org-protocol=, including keyboard shortcut support
- Add a Homebrew formula
- Docs, tests, CI (build,test,dependabot)
- Companion project on iOS to route =org-protocol://= links to chosen iOS apps with their own URL schemes, such as =beorg://=
* Potential scope
** Limited Shortcuts.app support
Currently Shortcuts.app can't use =emacsclient= in Emacs Plus due to socket/env related issues.
Support some way of opening a file or link via EmacsOpen either via CLI or a Siri Shortcut action.
* Out of scope
- No GUI
  - All user interactions should be via a share action, or the =emacsopen= CLI command.
  - All configuration should be a text file, probably TOML format.
  - All responses should be via stdout (CLI), macOS error notification/alert, and maybe logging.
- No AppleScript support
  - Use Emacs lisp instead: ~emacsopen ensure-client && emacslient -e ...~
* Background
This started as a discussion on an [[https://github.com/d12frosted/homebrew-emacs-plus/pull/783][Emacs Plus PR]] thread.
