#+title: EmacsOpen.app (Vaporware)
* Main idea
"Open thing in Emacs, do what I mean."

Share and open files, web links, web page selection (Safari), and =org-protocol://= links in Emacs on macOS, starting the Emacs daemon and opening a frame if necessary.
* Status: Planning / Vaporware
* CLI command =emacsopen=
- =ensure-client= (after which =emacsclient= should be ready, else error)
- =ensure-frame= (implies =ensure-client=)
- =activate-frame= (implies =ensure-frame=)
- =open-files [FILE...]=  (implies =activate-frame=)
- =open-org-protocol org-protocol://...= (implies =activate-frame=)
* Target Emacs flavours
Focusing on [[https://github.com/d12frosted/homebrew-emacs-plus][Emacs Plus]] v30 initially, but should work on Emacs flavours which manage a daemon via a =brew= service and communicate with Emacs via =emacsclient=.
* Out of scope
** No GUI
All user interactions should be via a share action, or the =emacsopen= CLI command.
All configuration should be a text file, probably TOML format.
All responses should be via stdout (CLI), macOS error notification/alert, and maybe logging.
** No AppleScript support
Use Emacs lisp instead: ~emacsopen ensure-client && emacslient -e ...~
* Potential roadblocks
** Can an unsigned macOS app invoke =emacsclient= to connect to Emacs when running?
Potential issues with permissions, and environment variables. Fails within Shortcuts.app.
** Can an unsigned macOS app start and stop a brew service?
Potential permissions issues.
* Background
This started as a discussion on an [[https://github.com/d12frosted/homebrew-emacs-plus/pull/783][Emacs Plus PR]] thread.
